### ISSUE TITLE
Error report for exile-diary 1.0.0

### ISSUE THREAD

**Issue by muriku** [Qt-dev/exile-diary#133]
Error:
```
TypeError: Object has been destroyed
    at EventEmitter.<anonymous> (C:\Users\murik\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\index.js:427:25)
    at EventEmitter.emit (node:events:513:28)
    at Tail.<anonymous> (C:\Users\murik\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\ClientTxtWatcher.js:126:37)
    at Tail.emit (node:events:513:28)
    at C:\Users\murik\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\node_modules\nodejs-tail\nodejs-tail.js:56:20
    at Array.forEach (<anonymous>)
    at C:\Users\murik\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\node_modules\nodejs-tail\nodejs-tail.js:54:43
    at FSReqCallback.wrapper [as oncomplete] (node:fs:675:5)
```
OS: Windows NT 10.0.22000

**Comment by Qt-dev** [comment]
I see, I will look into that for next version. I know where that bug is
Thanks for the report!

**Comment by muriku** [comment]
Yeah. very much love that u doing) thank you so much!)
