### ISSUE TITLE
Error report for exile-diary 1.0.1

### ISSUE THREAD

**Issue by Nyxet** [Qt-dev/exile-diary#144]
Getting absolutely spammed when doing 'anything' with error messages, entering zone, looking at stash, everything.

Error:
```
TypeError: Object has been destroyed
    at EventEmitter.<anonymous> (C:\zzPath of Exile Tools\Exile Diary\Exile Diary Reborn\resources\app.asar\build\main\index.js:427:25)
    at EventEmitter.emit (node:events:513:28)
    at Tail.<anonymous> (C:\zzPath of Exile Tools\Exile Diary\Exile Diary Reborn\resources\app.asar\build\main\modules\ClientTxtWatcher.js:126:37)
    at Tail.emit (node:events:513:28)
    at C:\zzPath of Exile Tools\Exile Diary\Exile Diary Reborn\resources\app.asar\node_modules\nodejs-tail\nodejs-tail.js:56:20
    at Array.forEach (<anonymous>)
    at C:\zzPath of Exile Tools\Exile Diary\Exile Diary Reborn\resources\app.asar\node_modules\nodejs-tail\nodejs-tail.js:54:43
    at FSReqCallback.wrapper [as oncomplete] (node:fs:675:5)
```
OS: Windows NT 10.0.22621

**Comment by Qt-dev** [comment]
Right, I hit that too but I have not found the proper fix yet. To get rid of it today, you need to turn the app off, and kill all remaining exile diary processes.
The reason it keeps on happening is that the app and the overlay lost connection. Restarting the app fully makes it start it proper again.

I'll have a fix for that once I can isolate why that happens and make it clean itself up

**Comment by Qt-dev** [comment]
-_- github just closed that by itself.

**Comment by Qt-dev** [comment]
Let me know if it still happens on 1.0.5
