### ISSUE TITLE
Object has been destroyed - Error report for exile-diary 1.0.5

### ISSUE THREAD

**Issue by mireigi** [Qt-dev/exile-diary#178]
Error:
```
TypeError: Object has been destroyed
    at EventEmitter.<anonymous> (E:\Steam\steamapps\common\Path of Exile\Exile Diary Reborn\resources\app.asar\build\main\index.js:434:25)
    at EventEmitter.emit (node:events:513:28)
    at Tail.<anonymous> (E:\Steam\steamapps\common\Path of Exile\Exile Diary Reborn\resources\app.asar\build\main\modules\ClientTxtWatcher.js:126:37)
    at Tail.emit (node:events:513:28)
    at E:\Steam\steamapps\common\Path of Exile\Exile Diary Reborn\resources\app.asar\node_modules\nodejs-tail\nodejs-tail.js:56:20
    at Array.forEach (<anonymous>)
    at E:\Steam\steamapps\common\Path of Exile\Exile Diary Reborn\resources\app.asar\node_modules\nodejs-tail\nodejs-tail.js:54:43
    at FSReqCallback.wrapper [as oncomplete] (node:fs:675:5)
```
OS: Windows NT 10.0.19045
App: exile-diary 1.0.5

**Comment by Qt-dev** [comment]
Hey there! Is it still happening in 1.1.0?

**Comment by Qt-dev** [comment]
Closing this one to consolidate reports for this error in one specific issue :)
