### ISSUE TITLE
table items has no column named original_value - Error report for exile-diary 1.4.15

### ISSUE THREAD

**Issue by ariyako** [Qt-dev/exile-diary#282]
Error:
```
SqliteError: table items has no column named original_value
    at Database.prepare (D:\POE-tools\ExileDairyReborn\Exile Diary Reborn\resources\app.asar\node_modules\better-sqlite3\lib\methods\wrappers.js:5:21)
    at D:\POE-tools\ExileDairyReborn\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:380:34
    at EventEmitter.<anonymous> (D:\POE-tools\ExileDairyReborn\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:320:32)
    at Object.onceWrapper (node:events:627:28)
    at EventEmitter.emit (node:events:513:28)
    at DBManager.runTasks (D:\POE-tools\ExileDairyReborn\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:312:35)
    at EventEmitter.<anonymous> (D:\POE-tools\ExileDairyReborn\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:292:18)
    at EventEmitter.emit (node:events:513:28)
    at D:\POE-tools\ExileDairyReborn\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:325:31
    at new Promise (<anonymous>)
```
OS: Windows NT 10.0.19045
App: exile-diary 1.4.15

**Comment by ariyako** [comment]
version 1.4.16 fix the problem. thanks!
