### ISSUE TITLE
NOT NULL constraint failed: items.category - Error report for exile-diary 1.4.16

### ISSUE THREAD

**Issue by Tsett** [Qt-dev/exile-diary#286]
Error:
```
SqliteError: NOT NULL constraint failed: items.category
    at D:\PoE\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:391:31
    at sqliteTransaction (D:\PoE\Exile Diary Reborn\resources\app.asar\node_modules\better-sqlite3\lib\methods\transaction.js:65:24)
    at D:\PoE\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:394:20
    at EventEmitter.<anonymous> (D:\PoE\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:327:32)
    at Object.onceWrapper (node:events:627:28)
    at EventEmitter.emit (node:events:513:28)
    at DBManager.runTasks (D:\PoE\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:319:35)
    at EventEmitter.<anonymous> (D:\PoE\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:299:18)
    at EventEmitter.emit (node:events:513:28)
    at D:\PoE\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:332:31
```
OS: Windows NT 10.0.22621
App: exile-diary 1.4.16

**Comment by Tsett** [comment]
Happens very often wehn I leave from a Map to my Hideout.

**Comment by Tsett** [comment]
Seems to happen shortlty after an Incubator is finished and you leave the map (maybe a second time?)

**Comment by Qt-dev** [comment]
Does this still happen with the latest version ?

**Comment by SNiLD** [comment]
There was another exception coming in this league, but that and this one has disappeared since the latest version of Exile Diary Reborn.

**Comment by Qt-dev** [comment]
That's good to hear. Feel free to reopen issues if another one pops up again.
