### ISSUE TITLE
NOT NULL constraint failed: items.category - Error report for exile-diary 1.4.16

### ISSUE THREAD

**Issue by SNiLD** [Qt-dev/exile-diary#287]
Error:
```
SqliteError: NOT NULL constraint failed: items.category
    at C:\Games\Path of Exile\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:391:31
    at sqliteTransaction (C:\Games\Path of Exile\Exile Diary Reborn\resources\app.asar\node_modules\better-sqlite3\lib\methods\transaction.js:65:24)
    at C:\Games\Path of Exile\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:394:20
    at EventEmitter.<anonymous> (C:\Games\Path of Exile\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:327:32)
    at Object.onceWrapper (node:events:627:28)
    at EventEmitter.emit (node:events:513:28)
    at DBManager.runTasks (C:\Games\Path of Exile\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:319:35)
    at EventEmitter.<anonymous> (C:\Games\Path of Exile\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:299:18)
    at EventEmitter.emit (node:events:513:28)
    at C:\Games\Path of Exile\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:332:31
```
OS: Windows NT 10.0.22621
App: exile-diary 1.4.16

**Comment by SNiLD** [comment]
Unclear when that exception occured. I closed PoE after completing Sanctum level without any flasks in my belt (if that helps).

**Comment by Tsett** [comment]
Duplicate to #286

**Comment by Qt-dev** [comment]
I'm closing this one to cleanup, but leaving 286 open
