### ISSUE TITLE
NOT NULL constraint failed: items.category - Error report for exile-diary 1.4.16

### ISSUE THREAD

**Issue by dobrowolsk** [Qt-dev/exile-diary#288]
Happens regularly, at least twice a day. Don't know when exactly or why.

Error:
```
SqliteError: NOT NULL constraint failed: items.category
    at C:\Users\USER\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:391:31
    at sqliteTransaction (C:\Users\USER\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\node_modules\better-sqlite3\lib\methods\transaction.js:65:24)
    at C:\Users\USER\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:394:20
    at EventEmitter.<anonymous> (C:\Users\USER\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:327:32)
    at Object.onceWrapper (node:events:627:28)
    at EventEmitter.emit (node:events:513:28)
    at DBManager.runTasks (C:\Users\USER\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:319:35)
    at EventEmitter.<anonymous> (C:\Users\USER\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:299:18)
    at EventEmitter.emit (node:events:513:28)
    at C:\Users\USER\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:332:31
```
OS: Windows NT 10.0.19045
App: exile-diary 1.4.16

**Comment by Qt-dev** [comment]
Hey there and thanks for the report. This happens when you pick up something that the app does not know how to categorize. I have a fix for that in dev but I have not had time to push it yet. Sorry about that >.<

**Comment by Qt-dev** [comment]
Hey there and thanks for the report. This happens when you pick up something that the app does not know how to categorize. I have a fix for that in dev but I have not had time to push it yet. Sorry about that >.<

**Comment by Qt-dev** [comment]
This should be fixed now. Feel free to reopen an issue if it still happens
