### ISSUE TITLE
NOT NULL constraint failed: items.category - Error report for exile-diary 1.4.16

### ISSUE THREAD

**Issue by darkmage06** [Qt-dev/exile-diary#289]
Error:
```
SqliteError: NOT NULL constraint failed: items.category
    at E:\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:391:31
    at sqliteTransaction (E:\Exile Diary Reborn\resources\app.asar\node_modules\better-sqlite3\lib\methods\transaction.js:65:24)
    at E:\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:394:20
    at EventEmitter.<anonymous> (E:\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:327:32)
    at Object.onceWrapper (node:events:627:28)
    at EventEmitter.emit (node:events:513:28)
    at DBManager.runTasks (E:\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:319:35)
    at EventEmitter.<anonymous> (E:\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:299:18)
    at EventEmitter.emit (node:events:513:28)
    at E:\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:332:31
```
OS: Windows NT 10.0.22631
App: exile-diary 1.4.16

**Comment by Qt-dev** [comment]
Thanks for the report. This happens when there's an item that is unrecognized by the app. 
I have a fix for that in dev but I'll have to make a new version to get rid of these. Sorry about that :)

**Comment by Qt-dev** [comment]
This should be fixed now. Feel free to reopen an issue if this still happens
