### ISSUE TITLE
NOT NULL constraint failed: items.category - Error report for exile-diary 1.4.16

### ISSUE THREAD

**Issue by Noctis-** [Qt-dev/exile-diary#291]
Error:
```
SqliteError: NOT NULL constraint failed: items.category
    at C:\Users\Noctis\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:391:31
    at sqliteTransaction (C:\Users\Noctis\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\node_modules\better-sqlite3\lib\methods\transaction.js:65:24)
    at C:\Users\Noctis\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:394:20
    at EventEmitter.<anonymous> (C:\Users\Noctis\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:327:32)
    at Object.onceWrapper (node:events:627:28)
    at EventEmitter.emit (node:events:513:28)
    at DBManager.runTasks (C:\Users\Noctis\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:319:35)
    at EventEmitter.<anonymous> (C:\Users\Noctis\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:299:18)
    at EventEmitter.emit (node:events:513:28)
    at C:\Users\Noctis\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\db\index.js:332:31
```
OS: Windows NT 10.0.19045
App: exile-diary 1.4.16

**Comment by Qt-dev** [comment]
This should be fixed now. Feel free to reopen an issue if it still happens
