### ISSUE TITLE
Error report for exile-diary 1.0.0-alpha.5

### ISSUE THREAD

**Issue by NokTham** [Qt-dev/exile-diary#83]
Error:
```ReferenceError: SettingsManager is not defined
    at getRatesFor (C:\Users\ZarkBit\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\ItemPricer.js:65:25)
    at Object.<anonymous> (C:\Users\ZarkBit\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\ItemPricer.js:611:42)
    at step (C:\Users\ZarkBit\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\ItemPricer.js:33:23)
    at Object.next (C:\Users\ZarkBit\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\ItemPricer.js:14:53)
    at C:\Users\ZarkBit\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\ItemPricer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\ZarkBit\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\ItemPricer.js:4:12)
    at Object.price (C:\Users\ZarkBit\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\ItemPricer.js:111:12)
    at C:\Users\ZarkBit\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\RunParser.js:697:61
    at step (C:\Users\ZarkBit\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\RunParser.js:33:23)
```
OS: Windows NT 10.0.17763

**Comment by Qt-dev** [comment]
Sorry about that. I built the app too fast like an idiot. I just re published a new package of alpha.5. Please redownload and install through that, the error should not happen again

**Comment by NokTham** [comment]
Thank you, fixed with the latest release :-)
